FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src
COPY dbt ./dbt
COPY data ./data
COPY quality ./quality
COPY scenarios ./scenarios

RUN pip install --no-cache-dir .

EXPOSE 8000

CMD ["dq-api"]
